language: node_js
node_js:
  - "0.10"
install:
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install
script: node_modules/.bin/intern-runner config=tests/intern
notifications:
  slack: blueraster:KRUNi2hoHOZc4v7c2Dse9zWF
